config/routes.rb
RedmineApp::Application.routes.draw do
  match 'project' => 'timelog#bulk_edit', :as => :project_stories, :via => [:get]
  
  # Lists of Scrummer Plugin Paths
    
  # Scrum Releases Planning path
  match '/scrum_releases_planning' => 'scrum_releases_planning#index', :as => :scrum_release_planing
  match '/scrum_releases_planning/show_release/:id' => 'scrum_releases_planning#show_release', :as => :show_scrum_release
  match '/scrum_releases_planning/:id/edit_release' => 'scrum_releases_planning#edit_release', :as => :edit_scrum_release
  match '/scrum_releases_planning/create' => 'scrum_releases_planning#create', :as => :create_scrum_release, :via => :post
  match '/scrum_releases_planning/set_issue_release' => 'scrum_releases_planning#set_issue_release', :as => :set_issue_release
  match '/scrum_releases_planning/:id' => 'scrum_releases_planning#update_release', :as => :update_scrum_release, :via => :put
  match '/scrum_releases_planning/:id/destroy_release' => 'scrum_releases_planning#destroy_release', :as => :destroy_scrum_release, :via => :delete
  
  # Sprint Planning path
  match '/scrum_sprints_planning' => 'scrum_sprints_planning#index', :as => :scrum_sprint_planing
  match '/scrum_sprints_planning/:id/edit_version' => 'scrum_sprints_planning#edit_version', :as => :edit_scrum_sprint
  match '/scrum_sprints_planning/add_version' => 'scrum_sprints_planning#add_version', :as => :add_scrum_sprint, :via => :post
  match '/scrum_sprints_planning/:id/destroy_version' => 'scrum_sprints_planning#destroy_version', :as => :destroy_scrum_sprint
  
  # User Stories path
  match '/scrum_userstories' => 'scrum_userstories#index', :as => :scrum_user_stories
  match '/scrum_userstories/statistics' => 'scrum_userstories#calculate_statistics', :as => :scrum_statistics
  match '/scrum_userstories/inline_add' => 'scrum_userstories#inline_add', :as => :inline_add, :via => [:post, :put]
  match '/scrum_userstories/issues_list' => 'scrum_userstories#issues_list', :as => :issues_list, :via => [:post, :delete]
  match '/scrum_userstories/update_single_field' => 'scrum_userstories#update_single_field', :as => :update_single_field
  match '/scrum_userstories/get_inline_issue_form' => 'scrum_userstories#get_inline_issue_form', :as => :get_inline_issue_form
  match '/scrum_userstories/refresh_inline_add_form' => 'scrum_userstories#refresh_inline_add_form', :as => :refresh_inline_add_form
  
  # Scrum Admin path
  match '/scrum_admin' => 'scrum_admins#index', :as => :scrum_admins
  match '/scrum_admin/update_custom_fields' => "scrum_admins#update_scrum_tracker_statuses", :as => :update_scrum_tracker_statuses, :via => :post
  match '/scrum_admin/update_scrum_trackers' => "scrum_admins#update_scrum_trackers", :as => :update_scrum_trackers, :via => :post
  match '/scrum_admin/update_weekly_vacations' => "scrum_admins#update_weekly_vacation", :as => :admin_weekly_vacation
  
  # Scrum Charts
  match '/projects/:project_id/scrum_charts(.:format)' => 'scrum_charts#index', :as => :scrum_charts
  match '/projects/:project_id/scrum_charts/update_chart' => 'scrum_charts#update_chart', :as => :update_chart
  
  # Vacations
  match '/vacations' => 'vacations#index', :as => :vacations
  match '/vacations/add_weekly_vacation' => 'vacations#weekly_vacation', :as => :weekly_vacation
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  match '/vacations/add_vacation' => 'vacations#add_vacation', :as => :add_vacation
  match '/vacations/:id/delete_vacation' => 'vacations#delete_vacation', :as => :delete_vacation, :via => :delete
end

app/controllers/scrum_releases_planning_controller.rb
class ScrumReleasesPlanningController < IssuesController
  unloadable
  # layout 'base'
  
  include ScrumUserstoriesController::SharedScrumConstrollers
  
  before_filter :find_scrum_project, :only => [:index, :destroy_release]
  prepend_before_filter :find_project, :only => [:create, :destroy_release, :edit_release, :show_release, :update_release, :set_issue_release]
  # By Mohamed Magdy
  # Filter before entering the index action to highlight the scrummer
  # menu tab
  before_filter :current_page_setter
  before_filter :build_new_issue_from_params, :only => :index
  
  # GET /releases
  # GET /releases.xml
  def index
    @query = IssueQuery.find_by_scrummer_caption("Release-Planning")
    # initialize_sort
    
    @release  = Release.new
    @releases = @project.releases
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @releases }
    end
  end

  # GET /releases/1
  # GET /releases/1.xml
  def show_release
    @release = Release.find(params[:id])

    respond_to do |format|
      format.html # show_release.html.erb
      format.xml  { render :xml => @release }
    end
  end

  # GET /releases/1/edit
  def edit_release
    @release = Release.find(params[:id])
  end

  # POST /releases
  # POST /releases.xml
  def create
    @query = IssueQuery.find_by_scrummer_caption("Release-Planning")
    # initialize_sort
    @release = Release.new(params[:release])
    @release.project_id = @project.id
  end

  # PUT /releases/1
  # PUT /releases/1.xml
  def update_release
    @release = Release.find(params[:id])

    respond_to do |format|
      if @release.update_attributes(params[:release])
        format.html { redirect_to(:action => 'index', :project_id => @project, :notice => 'Release was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit_release" }
        format.xml  { render :xml => @release.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def set_issue_release
    @issue = Issue.find params[:issue_id]
    @issue.init_journal(User.current)
    release_id = params[:release_id] != 'backlog' ? params[:release_id] : nil
    @issue.release_id = release_id
    @issue.save
    
    render :update do |page|
      page.visual_effect :highlight, "header-#{release_id}", :duration => 3
    end
    
  end

  # DELETE /releases/1
  # DELETE /releases/1.xml
  def destroy_release
    @release = @project.releases.find(params[:id])
    @release.destroy

    respond_to do |format|
      format.html { redirect_to scrum_release_planing_path(:project_id => @project.identifier) }
      format.js
    end
  end
  
  protected
  # By Mohamed Magdy
  # This methods sets the curret_page attribute to be used in the view 
  # and mark the current page in the scrummer menu
  def current_page_setter
    @current_page = :release_planning
  end
end

app/helpers/scrum_releases_planning_helper.rb
module ScrumReleasesPlanningHelper
  
  include ScrumUserstoriesHelper
  

  
end

app/views/scrum_releases_planning/_new.erb
<%= form_for @release, :url => {:controller => :scrum_releases_planning, :action => :create, :project_id => @project}, :remote => true do |f| %>

<div id='release_errors'>
</div>

<div class="box">
  <p>
    <%= f.label :name %><br/>
    <%= f.text_field :name %>
  </p>
  
  <p>
    <%= f.label :state %><br/>
  	<%= f.select :state, Release::RELEASE_STATUSES%>
  </p>
  
  <p style="float: left">
    <%= f.label :start_date %><br/>
    <%= f.text_field :start_date, :size => 10 %><%= calendar_for('release_start_date') %>
  </p>
  
  <p>
    <%= f.label :release_date %><br/>
    <%= f.text_field :release_date, :size => 10 %><%= calendar_for('release_release_date') %>
  </p>
  
  <p>
    <%= f.label :description %><br/>
    <%= f.text_area :description, :style => 'height:40px'%>
  </p>
  
  <p>
    <%= f.submit l(:button_create) %>
  </p>
</div>
<% end %>

app/views/scrum_releases_planning/_release.erb
  <tr id=<%= "release-#{release.id}"%> class='<%= "release #{cycle 'odd', 'even'} #{release.state.downcase}"%>' >
    <td class="name"><%=h link_to release.name, show_scrum_release_path(:id => release.id, :project_id => @project) %></td>
    <td><%=h release.start_date %></td>
    <td><%=h release.release_date %></td>
    <td><%=h release.state %></td>
    <td><%=h release.description %></td>
    <td><%=h pluralize(release.number_of_points, "point") %></td>
    <td class='buttons'>
        <%= link_to l(:button_edit), edit_scrum_release_path(:id => release.id, :project_id => @project),:class => 'icon icon-edit' %>
        <%= link_to l(:button_delete), destroy_scrum_release_path(release, :project_id => @project), :confirm => 'Are you sure?', :html =>{:class => 'icon icon-del'}, :method => :delete, :remote => true %></td>
  </tr>

app/views/scrum_releases_planning/_release_as_list.erb
<h2 id='header-<%= release_as_list.id %>' class='release-header'><%= release_as_list.name %></h2>
<div id='<%= release_as_list.id%>' class='list-parent' style="<%= release_as_list.issues.any? ? 'float: left;' : 'min-height:100px; min-width: 100%;'%>">
	<ul class='bachlog-list'>
		<% issues = release_as_list.issues.find(:all, :order => sort_clause) %>
		<% issues.each do |issue| %>
			<%= issue_li_tag issue  unless issue.test? || issue.task? %>
		<% end %>
	</ul>
</div>
<script>
	$("#<%= release_as_list.id%>").bind("DOMSubtreeModified", function() {
	   	var issuesCount = $(this).children().children().length;
		if(issuesCount > 0){
			$('#<%= release_as_list.id%>').css('min-height', '');
			$('#<%= release_as_list.id%>').css('float', 'left');
		} else {
			$('#<%= release_as_list.id%>').css('min-height', '100px'); 
			$('#<%= release_as_list.id%>').css('min-width', '100%');
			$('#<%= release_as_list.id%>').css('float', '');
		}
	});
</script>

app/views/scrum_releases_planning/_release_backlog.html.erb
<ul class='bachlog-list'>
	<% @issues.each do |issue| %>
		<%= issue_li_tag issue unless issue.test? || issue.task?%>
	<% end %>
</ul>

app/views/scrum_releases_planning/create.js.erb
<%- if @release.save %>
	$(".releases tr:last").after("<%= escape_javascript(render('release', :release => @release)) %>");
	$("#release_errors").html("");
	$(".releases tr:last").effect("highlight", {color:"#FFA"}, 3000);
<%- else %>
	$("#release_errors").html("<%= escape_javascript(error_messages_for('release')) %>");
<%- end %>

app/views/scrum_releases_planning/destroy_release.js.erb
$("#release-<%= @release.id %>").remove();
$("#header-<%= @release.id %>").remove();
$("#<%= @release.id %>").remove();

app/views/scrum_releases_planning/edit_release.html.erb
<% content_for :header_tags do %>
    <%= stylesheet_link_tag 'general.css', :plugin => 'redmine_scrummer' %>
<% end %>

<!-- Rendering the scrummer menu --> 
<%= render :partial => "scrum/scrummer_menu" %>
<!-- End by Mohamed Magdy -->

<h2>Edit Release</h2>

<%= labelled_form_for :release, @release, :url => {:action => 'update_release',:id => @release.id, :project_id => @project} do |f| %>

	<div id='release_errors'><%= error_messages_for('release') %></div>

  <div class="box tabular">
	  <p>
	    <%= f.text_field :name %>
	  </p>
	  <p>
	    <%= f.text_field :start_date, :size => 10 %><%= calendar_for('release_start_date') %>
	  </p>
	  <p>
	    <%= f.text_field :release_date, :size => 10 %><%= calendar_for('release_release_date') %>
	  </p>
	  <p>
	  	<%= f.select :state, Release::RELEASE_STATUSES%>
	  </p>
	  <p>
	    <%= f.text_area :description, :style => 'height:100px;width:500px'%>
	  </p>
	  <p>
	    <%= submit_tag l(:button_save) %>
	  </p>
  </div>
<% end %>

app/views/scrum_releases_planning/index.html.erb
<!-- Rendering the scrummer menu --> 
<%= render :partial => "scrum/scrummer_menu" %>

<h2>Releases Planning</h2>
<% content_for :header_tags do %>
	<%= stylesheet_link_tag 'general.css', :plugin => 'redmine_scrummer' %>
	<%= stylesheet_link_tag 'sticky_notes.css', :plugin => 'redmine_scrummer' %>
   	
	<%= javascript_include_tag 'context_menu.js'%>
	<%= javascript_include_tag 'scrum_shared', :plugin => 'redmine_scrummer' %>
  <%= javascript_include_tag 'jquery-ui.min.js', :plugin => 'redmine_scrummer' %>
	<%= javascript_include_tag 'scrum_shared', :plugin => 'redmine_scrummer' %>
  <%= javascript_include_tag 'jquery.cluetip.js', :plugin => 'redmine_scrummer' %>
  <%= javascript_include_tag 'jquery.cluetip.min.js', :plugin => 'redmine_scrummer' %>
  <%= javascript_include_tag 'jquery.hoverIntent.js', :plugin => 'redmine_scrummer' %>
  <%= javascript_tag "select_menu_item('scrum-release-planing');"%>
<% end %>

<br/>
<div>
  <fieldset id="inline-add" class="collapsible collapsed">
  	<br />
  	<legend onclick="toggleFieldset(this);"><%= l(:label_add_release_inline) %></legend>
  	<div id='inline_add_container' style="display:none">
  		<%= render :partial => 'new'%>
  	</div>
  </fieldset>

  <table class="list releases">
    <thead>
      <tr>
        <th><%= l(:name) %></th>
        <th><%= l(:start_date) %></th>
        <th><%= l(:field_release_date) %></th>
        <th><%= l(:field_state) %></th>
        <th><%= l(:field_description)%></th>
        <th><%= l(:number_of_points) + " (points)" %></th>
        <th style="width:30px"></th>
      </tr>
    </thead>
    <tbody id='releases'>
    <%= render :partial => 'release', :collection => @releases %>
    </tbody>
  </table>
</div>

<br/>

app/views/scrum_releases_planning/show.html.erb
<div id="scrum_menu">
	<!-- Rendering the scrummer menu --> 
	<%= render :partial => "scrum/scrummer_menu" %>
</div>


<h2>Show release</h2>

<p>
  <b>Name:</b>
  <%=h @release.name %>
</p>

<p>
  <b>Start date:</b>
  <%=h @release.start_date %>
</p>

<p>
  <b><%= l :field_release_date %></b>
  <%=h @release.release_date %>
</p>

<p>
  <b><%= l :field_state %></b>
  <%=h @release.state %>
</p>

<p>
  <b>Description:</b>
  <%=h @release.description %>
</p>


<%= link_to 'Edit', :action => 'edit', :id => @release.id, :project_id => @project %> |
<%= link_to 'Back', :action => 'index', :project_id => @project %>

app/views/scrum_releases_planning/show_release.html.erb
<% content_for :header_tags do %>
    <%= stylesheet_link_tag 'general.css', :plugin => 'redmine_scrummer' %>
<% end %>

<!-- Rendering the scrummer menu --> 
<%= render :partial => "scrum/scrummer_menu" %>

<div class="contextual">
<%= link_to l(:button_edit), edit_scrum_release_path(:id => @release.id, :project_id => @project), :class => 'icon icon-edit' %>
<%= link_to l(:button_delete), {:action => 'destroy_release', :id => @release.id, :project_id => @project}, :confirm => 'Are you sure?', :method => :delete, :class => 'icon icon-del' %>
</div>

<h2><%= @release.name %></h2>

<div id="roadmap">
<p>
  <b><%= l(:start_date) %></b>
  <%=h @release.start_date %>
</p>

<p>
  <b><%= l(:field_release_date) %></b>
  <%=h @release.release_date %>
</p>

<p>
  <b><%= l(:field_state) %></b>
  <%=h @release.state %>
</p>
<p>
  <b><%= l(:number_of_points) %></b>
  <%=h pluralize(@release.number_of_points, "point") %>
</p>

<p>
  <b><%= l(:description) %></b><br/>
  <%=h @release.description %>
</p>
</div>