config/routes.rb
RedmineApp::Application.routes.draw do
  match 'project' => 'timelog#bulk_edit', :as => :project_stories, :via => [:get]
  
  # Lists of Scrummer Plugin Paths
    
  # Scrum Releases Planning path
  match '/scrum_releases_planning' => 'scrum_releases_planning#index', :as => :scrum_release_planing
  match '/scrum_releases_planning/show_release/:id' => 'scrum_releases_planning#show_release', :as => :show_scrum_release
  match '/scrum_releases_planning/:id/edit_release' => 'scrum_releases_planning#edit_release', :as => :edit_scrum_release
  match '/scrum_releases_planning/create' => 'scrum_releases_planning#create', :as => :create_scrum_release, :via => :post
  match '/scrum_releases_planning/set_issue_release' => 'scrum_releases_planning#set_issue_release', :as => :set_issue_release
  match '/scrum_releases_planning/:id' => 'scrum_releases_planning#update_release', :as => :update_scrum_release, :via => :put
  match '/scrum_releases_planning/:id/destroy_release' => 'scrum_releases_planning#destroy_release', :as => :destroy_scrum_release, :via => :delete
  
  # Sprint Planning path
  match '/scrum_sprints_planning' => 'scrum_sprints_planning#index', :as => :scrum_sprint_planing
  match '/scrum_sprints_planning/:id/edit_version' => 'scrum_sprints_planning#edit_version', :as => :edit_scrum_sprint
  match '/scrum_sprints_planning/add_version' => 'scrum_sprints_planning#add_version', :as => :add_scrum_sprint, :via => :post
  match '/scrum_sprints_planning/:id/destroy_version' => 'scrum_sprints_planning#destroy_version', :as => :destroy_scrum_sprint
  
  # User Stories path
  match '/scrum_userstories' => 'scrum_userstories#index', :as => :scrum_user_stories
  match '/scrum_userstories/statistics' => 'scrum_userstories#calculate_statistics', :as => :scrum_statistics
  match '/scrum_userstories/inline_add' => 'scrum_userstories#inline_add', :as => :inline_add, :via => [:post, :put]
  match '/scrum_userstories/issues_list' => 'scrum_userstories#issues_list', :as => :issues_list, :via => [:post, :delete]
  match '/scrum_userstories/update_single_field' => 'scrum_userstories#update_single_field', :as => :update_single_field
  match '/scrum_userstories/get_inline_issue_form' => 'scrum_userstories#get_inline_issue_form', :as => :get_inline_issue_form
  match '/scrum_userstories/refresh_inline_add_form' => 'scrum_userstories#refresh_inline_add_form', :as => :refresh_inline_add_form
  
  # Scrum Admin path
  match '/scrum_admin' => 'scrum_admins#index', :as => :scrum_admins
  match '/scrum_admin/update_custom_fields' => "scrum_admins#update_scrum_tracker_statuses", :as => :update_scrum_tracker_statuses, :via => :post
  match '/scrum_admin/update_scrum_trackers' => "scrum_admins#update_scrum_trackers", :as => :update_scrum_trackers, :via => :post
  match '/scrum_admin/update_weekly_vacations' => "scrum_admins#update_weekly_vacation", :as => :admin_weekly_vacation
  
  # Scrum Charts
  match '/projects/:project_id/scrum_charts(.:format)' => 'scrum_charts#index', :as => :scrum_charts
  match '/projects/:project_id/scrum_charts/update_chart' => 'scrum_charts#update_chart', :as => :update_chart
  
  # Vacations
  match '/vacations' => 'vacations#index', :as => :vacations
  match '/vacations/add_weekly_vacation' => 'vacations#weekly_vacation', :as => :weekly_vacation
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  match '/vacations/add_vacation' => 'vacations#add_vacation', :as => :add_vacation
  match '/vacations/:id/delete_vacation' => 'vacations#delete_vacation', :as => :delete_vacation, :via => :delete
end

app/controllers/scrum_admins_controller.rb
class ScrumAdminsController < ApplicationController
  unloadable
  
  include ScrumUserstoriesController::SharedScrumConstrollers
  
  before_filter :require_admin
  before_filter :current_page_setter
  
  # GET /scrum_admins
  # GET /scrum_admins.xml
  def index
    @trackers = Tracker.find(:all, :conditions => ["is_scrum = ?", true], :order => 'position')
    @tracker_statuses = IssueStatus.find(:all, :conditions => ["is_scrum = ?", true], :order => 'position')
    @weekly_vacation = ScrumWeeklyNonWorkingDay.first || ScrumWeeklyNonWorkingDay.new
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @scrum_admins }
    end
  end

  def update_scrum_trackers
    params[:trackers].each do |tracker_attributes|
      tracker = Tracker.find(tracker_attributes[0])
      tracker.name = tracker_attributes[1][:name]
      tracker.short_name = tracker_attributes[1][:short_name]
      tracker.position = tracker_attributes[1][:position]
      tracker.color = tracker_attributes[1][:color]
      tracker.save
    end

    flash[:notice] = "Trackers successfuly update!"

    respond_to do |format|
      format.html { redirect_to(scrum_admins_path(:project_id => @project)) }
    end
  end

  def update_scrum_tracker_statuses
    params[:tracker_statuses].each do |status_attributes|
      status = IssueStatus.find(status_attributes[0])
      status.name = status_attributes[1][:name]
      status.short_name = status_attributes[1][:short_name]
      status.position = status_attributes[1][:position]
      status.color = status_attributes[1][:color]
      status.width = status_attributes[1][:width]
      status.save
    end

    flash[:notice] = "Tracker Statuses successfuly update!"

    respond_to do |format|
      format.html { redirect_to(scrum_admins_path(:project_id => @project)) }
    end
  end
  
  def update_weekly_vacation
    @weekly_vacation = ScrumWeeklyNonWorkingDay.first || ScrumWeeklyNonWorkingDay.new
    
    respond_to do |format|
      if @weekly_vacation.update_attributes(params[:scrum_weekly_non_working_day])
        format.html { redirect_to(scrum_admins_path, :notice => 'Weekly Vacation was successfully set!') }
        format.xml  { render :xml => @weekly_vacation, :status => :created, :location => @weekly_vacation }
      else
        format.html { render :action => "index" }
        format.xml  { render :xml => @weekly_vacation.errors, :status => :unprocessable_entity }
      end
    end
  end

  private
  
  def current_page_setter
    @current_page = :scrum_admin
  end
end

app/helpers/scrum_admins_helper.rb
module ScrumAdminsHelper
end

app/views/scrum_admins/index.html.erb
<%= content_for :header_tags do %>
    <%= stylesheet_link_tag 'general', :plugin => 'redmine_scrummer' %>
<% end %>

<h1 style="margin: 10px 0px 10px 0px;">Scrum Configurations</h1>

<h2>Weekly Non Working Days</h2>

<%= form_for(@weekly_vacation, :url => admin_weekly_vacation_path) do |f| %>
	<%= render 'scrum/errors', :object => @weekly_vacation %>
  
  <table class="fancy">
  	<tr>
  	  <% Date::DAYNAMES.each do |day| %>
  		<th><%= f.label day.downcase.to_sym %></th>
  		<% end %>
  	</tr>
  	<tr>
  	  <% Date::DAYNAMES.each do |day| %>
  		<td><%= f.check_box day.downcase.to_sym %></td>
  		<% end %>
  	</tr>
  </table>
  <p>
    <%= f.submit l(:save) %>
  </p>
<% end %>

<h2>Trackers</h2>
<%= form_tag(update_scrum_trackers_path(:project_id => @project), :method => :post) do %>
	<table class="fancy">
		<tr>
			<th><%= l(:tracker) %></th>
			<th><%= l(:name) %></th>
			<th><%= l(:short_name) %></th>
			<th><%= l(:order) %></th>
			<th><%= l(:color) %></th>
		</tr>
		<% @trackers.each do |tracker| %>
			<tr align="center">
				<td><%= tracker.scrummer_caption.to_s.gsub("-", " ").titleize %></td>
				<td><%= text_field_tag "trackers[#{tracker.id}][name]", tracker.name %></td>
				<td><%= text_field_tag "trackers[#{tracker.id}][short_name]", tracker.short_name %></td>
				<td><%= text_field_tag "trackers[#{tracker.id}][position]", tracker.position %></td>
				<td><%= text_field_tag "trackers[#{tracker.id}][color]", tracker.color %></td>
			</tr>
		<% end %>
	</table>
  <p>
    <%= submit_tag l(:save) %>
  </p>
<% end %>

<h2>Tracker Statuses</h2>
<%= form_tag(update_scrum_tracker_statuses_path(:project_id => @project), :method => :post) do %>
	<table class="fancy">
		<tr>
			<th><%= l(:tracker_status) %></th>
			<th><%= l(:name) %></th>
			<th><%= l(:short_name) %></th>
			<th><%= l(:order) %></th>
			<th><%= l(:color) %></th>
			<th><%= l(:width) %></th>
		</tr>
		<% @tracker_statuses.each do |tracker_status| %>
			<tr align="center">
				<td><%= tracker_status.scrummer_caption.to_s.gsub("-", " ").titleize %></td>
				<td><%= text_field_tag "tracker_statuses[#{tracker_status.id}][name]", tracker_status.name %></td>
				<td><%= text_field_tag "tracker_statuses[#{tracker_status.id}][short_name]", tracker_status.short_name %></td>
				<td><%= text_field_tag "tracker_statuses[#{tracker_status.id}][position]", tracker_status.position %></td>
				<td><%= text_field_tag "tracker_statuses[#{tracker_status.id}][color]", tracker_status.color %></td>
				<td><%= text_field_tag "tracker_statuses[#{tracker_status.id}][width]", tracker_status.width %></td>
			</tr>
		<% end %>
	</table>
  <p>
    <%= submit_tag l(:save) %>
  </p>
<% end %>