config/routes.rb
RedmineApp::Application.routes.draw do
  match 'project' => 'timelog#bulk_edit', :as => :project_stories, :via => [:get]
  
  # Lists of Scrummer Plugin Paths
    
  # Scrum Releases Planning path
  match '/scrum_releases_planning' => 'scrum_releases_planning#index', :as => :scrum_release_planing
  match '/scrum_releases_planning/show_release/:id' => 'scrum_releases_planning#show_release', :as => :show_scrum_release
  match '/scrum_releases_planning/:id/edit_release' => 'scrum_releases_planning#edit_release', :as => :edit_scrum_release
  match '/scrum_releases_planning/create' => 'scrum_releases_planning#create', :as => :create_scrum_release, :via => :post
  match '/scrum_releases_planning/set_issue_release' => 'scrum_releases_planning#set_issue_release', :as => :set_issue_release
  match '/scrum_releases_planning/:id' => 'scrum_releases_planning#update_release', :as => :update_scrum_release, :via => :put
  match '/scrum_releases_planning/:id/destroy_release' => 'scrum_releases_planning#destroy_release', :as => :destroy_scrum_release, :via => :delete
  
  # Sprint Planning path
  match '/scrum_sprints_planning' => 'scrum_sprints_planning#index', :as => :scrum_sprint_planing
  match '/scrum_sprints_planning/:id/edit_version' => 'scrum_sprints_planning#edit_version', :as => :edit_scrum_sprint
  match '/scrum_sprints_planning/add_version' => 'scrum_sprints_planning#add_version', :as => :add_scrum_sprint, :via => :post
  match '/scrum_sprints_planning/:id/destroy_version' => 'scrum_sprints_planning#destroy_version', :as => :destroy_scrum_sprint
  
  # User Stories path
  match '/scrum_userstories' => 'scrum_userstories#index', :as => :scrum_user_stories
  match '/scrum_userstories/statistics' => 'scrum_userstories#calculate_statistics', :as => :scrum_statistics
  match '/scrum_userstories/inline_add' => 'scrum_userstories#inline_add', :as => :inline_add, :via => [:post, :put]
  match '/scrum_userstories/issues_list' => 'scrum_userstories#issues_list', :as => :issues_list, :via => [:post, :delete]
  match '/scrum_userstories/update_single_field' => 'scrum_userstories#update_single_field', :as => :update_single_field
  match '/scrum_userstories/get_inline_issue_form' => 'scrum_userstories#get_inline_issue_form', :as => :get_inline_issue_form
  match '/scrum_userstories/refresh_inline_add_form' => 'scrum_userstories#refresh_inline_add_form', :as => :refresh_inline_add_form
  
  # Scrum Admin path
  match '/scrum_admin' => 'scrum_admins#index', :as => :scrum_admins
  match '/scrum_admin/update_custom_fields' => "scrum_admins#update_scrum_tracker_statuses", :as => :update_scrum_tracker_statuses, :via => :post
  match '/scrum_admin/update_scrum_trackers' => "scrum_admins#update_scrum_trackers", :as => :update_scrum_trackers, :via => :post
  match '/scrum_admin/update_weekly_vacations' => "scrum_admins#update_weekly_vacation", :as => :admin_weekly_vacation
  
  # Scrum Charts
  match '/projects/:project_id/scrum_charts(.:format)' => 'scrum_charts#index', :as => :scrum_charts
  match '/projects/:project_id/scrum_charts/update_chart' => 'scrum_charts#update_chart', :as => :update_chart
  
  # Vacations
  match '/vacations' => 'vacations#index', :as => :vacations
  match '/vacations/add_weekly_vacation' => 'vacations#weekly_vacation', :as => :weekly_vacation
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  match '/vacations/add_vacation' => 'vacations#add_vacation', :as => :add_vacation
  match '/vacations/:id/delete_vacation' => 'vacations#delete_vacation', :as => :delete_vacation, :via => :delete
end

app/helpers/scrum_userstories_helper.rb
module ScrumUserstoriesHelper
			
	#unloadable # prevent it from being unloaded in development mode
						 # other wise, a stack overflow exception will be 
						 # thrown due to the alias method chain being called twice
	
	include CustomFieldsHelper unless included_modules.include? CustomFieldsHelper
	
	def column_short_header(column)
	  caption = column.caption
	  
	  short_headers = {l("field_remaining_hours")        => l("short_field_remaining_hours"),
	                   l("field_story_size")  => l("short_field_story_size"),
	                   l("field_estimated_hours") => l("short_field_estimated_hours"),
                     l("field_business_value") => l("short_field_business_value")}

    title = {l("short_field_remaining_hours")        => l("remaining_hours"),
             l("short_field_story_size")  => l("story_size"),
             l("short_field_estimated_hours") => l("estimated_hours")}
	                   
    caption = short_headers[caption] || caption
    content_tag('th', caption, :title => title[caption])
  end
  
	def custom_field_tag_with_add_class_to_float_inputs(name, custom_value)	
	  custom_field = CustomField.find(custom_value.custom_field_id)
    field_name = "#{name}[custom_field_values][#{custom_field.id}]"
    field_id = "#{name}_custom_field_values_#{custom_field.id}"

    field_format = Redmine::CustomFieldFormat.find_by_name(custom_field.field_format)
    
    case field_format.try(:edit_as)
    when "float"    	    
    	text_field_tag(field_name, custom_value.value, :id => field_id, :class => 'custom_field_float_type')
    else
      custom_field_tag_without_add_class_to_float_inputs(name, custom_value)
    end
  end
	alias_method_chain :custom_field_tag, :add_class_to_float_inputs  unless method_defined?(:custom_field_tag_without_add_class_to_float_inputs)
 	
 	
  
  def scrummy_column_content(column, issue)
  	
    if !issue[:tracker][:is_scrum]
      # fail back to old redmine logic
      return column_content(column, Issue.find(issue["id"]))
    end
      
    if column.name == :status
      content = issue[:status][:short_name].upcase 
  	  
      "<div title='#{issue[:status][:name]}' align='center' class='status #{issue[:status][:scrummer_caption]}' id='issue-#{issue["id"]}-status' data-statuses=\"#{issue_allowed_statuses(issue)}\"><b>" + content.to_s + "</b></div>"  	
    elsif (column.name == :subject)
  	  prefix = if issue[:children].empty?
  	    "<span>&nbsp;&nbsp;</span>"
      else
        "<span class=\"expander\" onclick=\"toggleScrumRowGroup(this); return false;\" onmouseover=\"$(this).addClass('hover')\" onmouseout=\"$(this).removeClass('hover')\">&nbsp;&nbsp;</span>"    
      end
      
      tracker = issue[:tracker]
      
  		"<div class='prefix'>#{prefix}<b><span class='issues-list-issue-id'>##{issue["id"].to_s}</span>" +
  		"<span class='tracker'>#{tracker[:name]}</span></b>:</div>" +
  		"<div >&nbsp;#{subject_content(issue)}</div>" 
    elsif [:story_size, :business_value].include?(column.name) 
      issue_has_children = issue[:children].any?  
      
      
      
      if (accept_field = issue[column.name.to_s] || issue_has_children )
        value = issue[column.name.to_s]
        
        if accept_field && (column.name == :business_value || !issue_has_children || (value != nil && value.to_f == 0.0) )
          content = value.to_f > 0 ? value : ' '*3
          content = format_story_size(content) if column.name == :story_size && content.is_a?(Float)
          css_class = 'edit' unless column.name == :story_size
          format = 'float'  unless column.name == :story_size
          content = "<div align='center' class='#{css_class} #{format} #{column.name}-container' id='issue-#{issue["id"]}-field-#{column.name}'>" + content.to_s + "</div>"
        else
          if column.name == :remaining_hours
            output_content = "&Sigma;" + value.to_s
          else
            output_content = format_story_size value.to_f
          end
          content = value.to_f > 0 ? "<span align='center' class='accumelated-result'>#{output_content}</span>" : '&nbsp;';
        end
      else
        # tasks, defects etc shouldn't display story size
        content = ''
      end
      
      content.to_s
      
    elsif [:actual_hours, :remaining_hours].include?(column.name)
      value = issue[column.name.to_s]
      value ||= 0
      
      elem_id = if column.name == :actual_hours
        issue["id"].to_s+"-"+column.name.to_s
      else
        "issue-" + issue["id"].to_s + "-field-" + column.name.to_s
      end      
      
      edit_method = column.name == :actual_hours ? "addition" : ""
                     
      output_value = value > 0 ? value.round(2).to_s : ""
      if issue[:time_trackable]
        content = "<div align='center' class='edit float #{edit_method}' id='issue-#{elem_id}'>" + output_value + "</div>"
      else
  		  output_value = "&Sigma;" + output_value if value > 0
        content = "<div align='center' class='accumelated-result' id='issue-#{elem_id}'>" + output_value + "</div>"
      end
      
  		content
    elsif column.name == :fixed_version

      if(issue["fixed_version_id"])
        version = issue[:fixed_version]
        link_to(h(version), {:controller => 'versions', :action => 'show', :id => issue["fixed_version_id"] })	     
      else
        ""
      end
    else
      issue[column.name] ? issue[column.name] : ""
    end
    
  end
  
  def issue_accumelated_custom_values issue, custom_field
  	format = custom_field.field_format
    result = 0.0
  	
  	if issue[:children].any? #&& issue.children.any?{|c| c.tracker.custom_fields.include?(custom_field)}  
  		issue[:children].each do |child|
  			result += issue_accumelated_custom_values(child, custom_field)
  		end
    end
      		
  	if result == 0.0
  		custom_value = issue.custom_value_for custom_field
  		value = custom_value ? custom_value.value : '' 
  		
  		result=(format == "float" ? value.to_f : value.to_i)  		
  	end
  	
  	result
  end
  
  def custom_column_exists_in_issue? custom_column, issue
  	issue.custom_values.collect{|value| value.custom_field_id}.include? custom_column.custom_field.id
  end
  
	def scrummer_image_path path
		'../plugin_assets/redmine_scrummer/images/' + path
	end
	
  def to_jss(string)
    string.gsub("\n","\\n")
  end
  
  def get_inline_issue_div_id
    inline_issue_div_id = @issue.new_record? ? "inline_edit_for_#{@issue["id"]}" : "new_issue_inline_div"
    inline_issue_div_id = @parent_issue ? "inline_add_child_for_#{@parent_issue["id"]}" : inline_issue_div_id
  end
  
  def subject_content(issue)
    subject = issue["subject"]
    
    description = issue["description"].gsub("'","\'")
    
    options = {:title=>"#{h(subject)}|#{h(description)}", :class=>'subject-contents'}
    
    link_to(h(subject), {:controller => 'issues', :action => 'show', :id => issue["id"] }, options)
  end
  
  def build_params_for_context_menu
    {:controller => params[:controller], :project_id => @project}
  end
  
  def issue_li_tag(issue)
    unit = issue.userstory? ? "pt":"hr"
    
    if issue.userstory?
      value = issue.story_size
    else 
      value = issue.remaining_hours
    end
    
    "<li class='issue' id='#{issue["id"]}'> 
      <a target='_blank' class='issue #{issue.tracker.try(:scrummer_caption).to_s.downcase}-issue' href='issues/#{issue["id"]}'> 
      <h2>##{issue["id"]}: #{issue.tracker.short_name}</h2>
      <p>#{truncate(issue.subject, :length => 30)}</p> 
      <p><span style='color: #444; float: right;'>#{pluralize(value, unit)}</span></p> 
      </a> 
     </li>"
  end
  
  def scrum_user_stories_manipulate_inline
    @scrum_user_stories_manipulate_inline ||= User.current.allowed_to?(:scrum_user_stories_manipulate_inline, @project)
  end

  def scrum_user_stories_add_inline
    @scrum_user_stories_add_inline ||= User.current.allowed_to?(:scrum_user_stories_add_inline, @project)
  end
  
  def issue_allowed_statuses(issue)
    statuses = issue[:tracker][:issue_statuses].inject("{") do |memo, status|
      unless status.scrummer_caption.blank?
        memo += "'" + status.short_name + "':'" + status.name + "', "
      end
      
      memo
    end

    statuses += "'selected':'" + issue[:status][:short_name] + "'}"
    statuses
  end
  
  def storysize_possible_values
    possible_sizes = ""
    Scrummer::Constants::StorySizes.each do |value|
      possible_sizes += "'" + value.to_f.to_s + "':'" + value.to_s + "', "
    end
    possible_sizes
  end

  def format_story_size(value)
    if ((value - value.to_i) == 0) 
      value.to_i
    else
      value
    end
  end
end

app/views/scrum_userstories/_inline_add.erb
<% inline_issue_div_id = get_inline_issue_div_id %>

<% tracker_field_id    = @issue.new_record? ? "issue_tracker_id" : "issue_tracker_id_for_#{@issue.id}" %>
<% tracker_field_id    = @parent_issue ? "issue_tracker_id_child_for_#{@parent_issue.id}" : tracker_field_id %>

<% inline_form_id      = @issue.new_record? ? "issue-form" : "inline_edit_form_for_#{@issue.id}" %>
<% inline_form_id      = @parent_issue ? "add_inline_child_form_for_#{@parent_issue.id}" : inline_form_id %>

<% issue_id      			 = @issue ? @issue.id : nil %>
<% hide_cancel 				||= false %>

<% list_id ||= 'issues_list' %>
<% from_sprint ||= 'issues_list' %>

<% editor_id = SecureRandom.uuid %>

<div id='<%= inline_issue_div_id%>' class='inline-issue-add'>
	<div id= <%="errors_for_#{inline_issue_div_id}"%> ></div>
	<%= form_for @issue, :url => {:controller => :scrum_userstories, :action => :inline_add, :list_id => list_id, :from_sprint => from_sprint},
														 :html => {:id => inline_form_id}, :oncomplete => "$('#selected_sprint').remove();", :remote => true do |f|%>
	
	<%= hidden_field_tag :id, @issue.id unless @issue.new_record? %>
	<%= f.hidden_field :project_id, :value => @project.id %>
	<%= f.hidden_field :priority_id, :value => IssuePriority.default.id %>
		
	<div class='scrum_issue_inline_fields'>
		<div class='scrum_issue_inline_field'>
			
			
			<%= select_tag "issue[tracker_id]", options_from_collection_for_select(@project.trackers.scrummer, 'id', 'name', @issue.tracker.try(:id)), :id => tracker_field_id %>

      <%= f.select :assigned_to_id, @project.members.map{|m| [m.name, m.user.id]}, :include_blank => l("field_assigned_to") %>
      
      <%= f.select :fixed_version_id, @issue.project.versions.map{|v| [v.name, v.id]}, {:include_blank => l("field_fixed_version")}, :class => "sprint_select" %>
	  
      <%= f.select :release_id, @project.releases.map{|r| [r.name, r.id]}, :include_blank => l("field_release_id") %>
		</div>
		<div class='scrum_issue_inline_field scrum_issue_row'>
		  <div class='scrum_issue_inline_control'>
				<%= f.label :subject, l("field_subject"), :class => "scrum_issue_inline_label" %>
				<div class='scrum_issue_inline_control'> 
					<%= f.text_field :subject, :size => 40 %>
				</div>
		  </div>
			
		  <div class='scrum_issue_inline_control'>
		    <%= f.label :parent_issue_id, l("field_parent_issue"), :class => "scrum_issue_inline_label", :style=>"padding-left:5px;" %>
		    <div class='scrum_issue_inline_control'> 
			  <%= f.text_field :parent_issue_id, :size => 5 %>
		    </div>
      	  </div>
		</div>
		
	  <div class='scrum_issue_inline_field scrum_issue_row'>
		<% if @issue.time_trackable? %>
			<div>
				<%= f.label :estimated_hours, l("short_field_estimated_hours"), :class => "scrum_issue_inline_label" %>
				<div class='scrum_issue_inline_control'> 
					<%= f.text_field :estimated_hours, :class => 'inline_issue_field_float_type' %>
				</div> 
			</div>
			
			<div>
        <%= f.label :remaining_hours, l("remaining_hours"), :class => "scrum_issue_inline_label" %>
        <div class='scrum_issue_inline_control'> 
          <%= f.text_field :remaining_hours, :class => 'inline_issue_field_float_type' %>
        </div> 
      </div>
		<% end %>
		
		<% if @issue.accept_story_size? %>
		  <div>
        <%= f.label :story_size, l("short_field_story_size"), :class => "scrum_issue_inline_label" %>
        <div class='scrum_issue_inline_control'> 
          <% story_size = f.object.story_size %>
          <% selected_story_size = ((story_size % 1 > 0.0) ? story_size : story_size.to_i) %>
          <%= f.select :story_size, Scrummer::Constants::StorySizes, :selected => selected_story_size %>
        </div> 
      </div>
      
      <div>
        <%= f.label :business_value, l("business_value"), :class => "scrum_issue_inline_label" %>
        <div class='scrum_issue_inline_control'> 
          <%= f.text_field :business_value, :class => "inline_issue_field_float_type" %>
        </div> 
      </div>
		<% end %>
		
		
		
		<% @issue.unduplicated_custom_values.each do |value| %>
		  <% if !@issue.new_record? %>
			<div class='scrum_issue_inline_field'>
				<%= custom_field_tag_with_label :issue, value %>
			</div>
			<% end %>
		<% end -%>			
			
		</div>
		
		<div class='scrum_issue_inline_field scrum_issue_row'>
			<%= f.label :description, l("field_description"), :class => "scrum_issue_inline_label" %>
			<div class='scrum_issue_inline_control'>
                <% text_area_id = editor_id %>
				<%= f.text_area :description, :rows => 7, :cols => 70, :class => 'wiki-edit', :id => "#{text_area_id}-inline-add-textarea"  %><%= wikitoolbar_for "#{text_area_id}-inline-add-textarea" %>
			</div>
		</div>
		
		<div class='scrum_issue_inline_submit'>	
			<%= f.submit %>
			<% unless hide_cancel %>
				<%= submit_tag "Cancel", :type => 'button', :onclick => 'cancelInlineChild(this)' %>
			<% end %>
		</div>
	</div>
	
	<%end%>
</div>
<script>

  $("#<%= tracker_field_id %>").observe_field(0, function() {
    $.get("<%= refresh_inline_add_form_path(:project_id => @project, :id => @issue, :list_id => list_id, :from_sprint => from_sprint, :hide_cancel => hide_cancel, :div => inline_issue_div_id) %>", $(this).closest("form").serialize());
  });
    
	$(".sprint_select").change(function(){
		$('#selected_sprint').remove();
		var hiddenField;
		if($(this).find(":selected").text() == "Target version" && $("#backlog").length > 0){
			hiddenField = '<input type="hidden" id= "selected_sprint" name="selected_sprint" value="backlog" />';
			$(this).parent().parent().parent().append(hiddenField);
		} else{
			hiddenField = '<input type="hidden" id= "selected_sprint" name="selected_sprint" value="sprint-' + $(this).val() + '" />';
		}
		$(this).parent().parent().parent().append(hiddenField);
	});
	
    
    CKEDITOR.on( 'instanceLoaded', function( evt ) {
        // The chameleon feature is not for IE quirks.
        if ( CKEDITOR.env.ie && CKEDITOR.env.quirks )
            return;
        var editor = evt.editor;
        var width = 1000,
            height = 250;

        editor.resize(width,height);
    });

    $("#placeholder-<%=issue_id%> td[colspan='9']").css('style="display: table-cell !important;"');

    $(document).ready(function () {
		if($("#backlog").length > 0){
			$("#<%= inline_form_id %>").append('<input type="hidden" id= "selected_sprint" name="selected_sprint" value="backlog" />')
		}
	});
</script>

app/views/scrum_userstories/_inline_add_version.erb
<% version ||= @project.versions.build %>

<% remote_form_for :version, :url => {:controller => :scrum_userstories, :action => :inline_add_version, :project_id => @project} do |f| %>

	<div id='version_errors'></div>
	<!--%= error_messages_for 'version' %-->
	
	<div class="box">
	<p>
	<%= f.label :name, l("field_name"), :class => "scrum_version_inline_label" %>
	<%= f.text_field :name, :size => 55, :required => true %>
	</p>
	
	<p>
	<%= f.label :description, l("field_description"), :class => "scrum_version_inline_label" %>
	<%= f.text_field :description, :size => 55 %>
	</p>
	
	<p>
	<%= f.label :status, l("field_status"), :class => "scrum_version_inline_label" %>
	<%= f.select :status, Version::VERSION_STATUSES.collect {|s| [l("version_status_#{s}"), s]} %>
	</p>
	
	<p>
	<%= f.label :wiki_page_title, l("label_wiki_page"), :class => "scrum_version_inline_label" %>
	<%= f.text_field :wiki_page_title, :label => :label_wiki_page, :size => 55, :disabled => @project.wiki.nil? %>
	</p>
	
	<p>
	<%= f.label :effective_date, l("field_effective_date"), :class => "scrum_version_inline_label" %>
	<%= f.text_field :effective_date, :size => 10 %><%= calendar_for('version_effective_date') %>
	</p>
	
	<p>
	<%= f.label :sharing, l("field_sharing"), :class => "scrum_version_inline_label" %>
	<%= f.select :sharing, version.allowed_sharings.collect {|v| [format_version_sharing(v), v]} %>
	</p>
	
	<% version.custom_field_values.each do |value| %>
		<p class='version_custon_field_label'><%= custom_field_tag_with_label :version, value %></p>
	<% end %>
	
	<%= f.submit %>

<% end %>
</div>

app/views/scrum_userstories/_issue_row.html.erb
<% level = issue[:level] %>

<tr id="issue-<%= issue["id"] %>" level="<%= level.to_s %>" class="<%= issue[:tracker][:scrummer_caption].to_s.downcase %>-issue hascontextmenu <%= cycle('odd', 'even') %> <%= level > 0 ? "idnt idnt-#{level}" : nil %> <%= (issue[:children] && issue[:children].length > 0) ? "group open" : nil%>">
	<% if hierarchy %>	
	  <td class="select-issue-td checkbox hide-when-print"><%= check_box_tag("ids[]", issue["id"], false, :id => nil) %></td>
	    <% end %>
	  
	  <% query.columns.each do |column| %>
	    <% next if(column.name == :id) %>
	  	<td class='<%= column.css_classes%>'>
	  		<%= scrummy_column_content(column, issue).html_safe %>
	  	</td>
	  <% end %>    
	  
	<%= hidden_field_tag("position-" + issue["id"].to_s, issue[:position]) %>
	<td class='issue-actions'>
		
	  	<!--Remove 'add_child' form task and test trackers -->
	  	<%if ! [:task, :test, :spike].include?( issue[:tracker][:scrummer_caption]) %>
	  		<%= link_to image_tag(scrummer_image_path('add_issue.png') ), get_inline_issue_form_path(:list_id => list_id, :project_id => @project.id, :parent_issue_id => issue["id"]), :remote => true  if scrum_user_stories_add_inline %>
			<%end%>
	  	<%= link_to image_tag(scrummer_image_path('edit_issue.png') ), get_inline_issue_form_path(:list_id => list_id, :from_sprint => from_sprint, :project_id => @project.id, :issue_id => issue["id"]), :remote => true if scrum_user_stories_manipulate_inline %>
	
	  	<% if scrum_user_stories_manipulate_inline %>	
		  	<% issues_list_url = url_for(:controller => :scrum_userstories, :action => :issues_list, :project_id => @project, :list_id => 'issues_list', :update => list_id) %>
		  	<%= link_to image_tag( scrummer_image_path('remove_issue.png') ), 
		  										 issue_path(issue["id"], :back_url => URI.encode(issues_list_url), :query_id => query.id, :project_id => @project, :list_id => list_id, :todo => :destroy),
		  										 :method => :delete, :confirm => "Are you sure?", :remote => true %>
	  	<% end%>
	  </td>	    
	<!-- The following Tr is sued as a place holder for inline-add-child -->
</tr>

app/views/scrum_userstories/_statistics.html.erb
<% @statistics ||= { :total_story_size => "", :total_estimate => "", :total_actual => "", :total_remaining => "" } -%>

<div id="statistics">
  <h3><%= l(:label_statistics) %></h3>
  <div class="label"><%= l(:label_total_points) %></div>
  <span class="value"><%= @statistics[:total_story_size] %></span>
  <br/>
  
  <div class="label"><%= l(:label_total_estimation) %></div>
  <span class="value"><%= @statistics[:total_estimate] %></span>
  <br/>
  
  <div class="label"><%= l(:label_total_remaining) %></div>
  <span class="value"><%= @statistics[:total_remaining] %></span>
  <br/>
  
  <div class="label"><%= l(:label_total_actual) %></div>
  <span class="value"><%= @statistics[:total_actual].blank? ? "": @statistics[:total_actual].to_f.round(2) %></span>
</div>

app/views/scrum_userstories/get_inline_issue_form.js.erb
$("#issue-<%= @issue_id %>-inline-child").html("<%= escape_javascript(render('inline_add', :list_id => params[:list_id], :from_sprint => params[:from_sprint])) %>");
$("#placeholder-<%=@issue_id%> td[colspan='9']").css("display", "table-cell");
$("#placeholder-8328 form  .scrum_issue_inline_fields .scrum_issue_inline_submit input").on('click',function (e) {
    $("#placeholder-<%=@issue_id%> td[colspan='9']").css("display", "none");
});

app/views/scrum_userstories/inline_add.js.erb
$("#<%= params[:list_id] %>").html("<%= escape_javascript(render(@partial_list, :issues => @issues, :query => @query, :list_id => params[:list_id], :from_sprint => params[:list_id]).html_safe) %>");
$("#errors_for_<%= @div_name %>").html("");       
$("#flash-temp").html("<%= escape_javascript(render_flash_messages) %>");
$("#flash_notice").remove();

app/views/scrum_userstories/issues_list.js.erb
$("#<%= params[:update] %>").html("<%= escape_javascript(render('list', :list_id => params[:list_id])) %>")

app/views/scrum_userstories/refresh_inline_add_form.js.erb
$("#<%= @div %>").html("<%= escape_javascript(render(:partial => 'inline_add', :locals => {:list_id => params[:list_id], :from_sprint => params[:from_sprint], :hide_cancel => params[:hide_cancel]}))%>")

app/views/scrum_userstories/render_error_html_for_inline_add.js.erb
$("#errors_for_<%= get_inline_issue_div_id %>").html("<%= escape_javascript(@error_html) %>")    

app/views/scrum_userstories/update_issue_and_parents.js.erb
<% level = params[:hierarchy] == "true" ? @issue[:level] : 0 %>
$("#issue-<%= @issue["id"].to_s %>").replaceWith("<%= escape_javascript(render('issue_row', :issue => @issue, :hierarchy => params[:hierarchy] == "true", :query => @query, :level => level, :list_id => params[:list_id], :from_sprint => params[:from_sprint])) %>")

<% parent = @issue[:parent]%>
<% while parent do  %>
	<% level = params[:hierarchy] == "true" ? parent[:level] : 0 %>
 	$("#issue-<%= parent["id"].to_s %>").replaceWith("<%= escape_javascript(render('issue_row', :issue => parent, :hierarchy => params[:hierarchy] == "true", :query => @query, :level => level, :list_id => params[:list_id], :from_sprint => params[:from_sprint]))
%>")
<%		parent = parent[:parent] %>
<% end %>

enableInlineEdit();

app/views/scrum_userstories/update_single_field.html.erb
<%= @value %>