config/routes.rb
RedmineApp::Application.routes.draw do
  match 'project' => 'timelog#bulk_edit', :as => :project_stories, :via => [:get]
  
  # Lists of Scrummer Plugin Paths
    
  # Scrum Releases Planning path
  match '/scrum_releases_planning' => 'scrum_releases_planning#index', :as => :scrum_release_planing
  match '/scrum_releases_planning/show_release/:id' => 'scrum_releases_planning#show_release', :as => :show_scrum_release
  match '/scrum_releases_planning/:id/edit_release' => 'scrum_releases_planning#edit_release', :as => :edit_scrum_release
  match '/scrum_releases_planning/create' => 'scrum_releases_planning#create', :as => :create_scrum_release, :via => :post
  match '/scrum_releases_planning/set_issue_release' => 'scrum_releases_planning#set_issue_release', :as => :set_issue_release
  match '/scrum_releases_planning/:id' => 'scrum_releases_planning#update_release', :as => :update_scrum_release, :via => :put
  match '/scrum_releases_planning/:id/destroy_release' => 'scrum_releases_planning#destroy_release', :as => :destroy_scrum_release, :via => :delete
  
  # Sprint Planning path
  match '/scrum_sprints_planning' => 'scrum_sprints_planning#index', :as => :scrum_sprint_planing
  match '/scrum_sprints_planning/:id/edit_version' => 'scrum_sprints_planning#edit_version', :as => :edit_scrum_sprint
  match '/scrum_sprints_planning/add_version' => 'scrum_sprints_planning#add_version', :as => :add_scrum_sprint, :via => :post
  match '/scrum_sprints_planning/:id/destroy_version' => 'scrum_sprints_planning#destroy_version', :as => :destroy_scrum_sprint
  
  # User Stories path
  match '/scrum_userstories' => 'scrum_userstories#index', :as => :scrum_user_stories
  match '/scrum_userstories/statistics' => 'scrum_userstories#calculate_statistics', :as => :scrum_statistics
  match '/scrum_userstories/inline_add' => 'scrum_userstories#inline_add', :as => :inline_add, :via => [:post, :put]
  match '/scrum_userstories/issues_list' => 'scrum_userstories#issues_list', :as => :issues_list, :via => [:post, :delete]
  match '/scrum_userstories/update_single_field' => 'scrum_userstories#update_single_field', :as => :update_single_field
  match '/scrum_userstories/get_inline_issue_form' => 'scrum_userstories#get_inline_issue_form', :as => :get_inline_issue_form
  match '/scrum_userstories/refresh_inline_add_form' => 'scrum_userstories#refresh_inline_add_form', :as => :refresh_inline_add_form
  
  # Scrum Admin path
  match '/scrum_admin' => 'scrum_admins#index', :as => :scrum_admins
  match '/scrum_admin/update_custom_fields' => "scrum_admins#update_scrum_tracker_statuses", :as => :update_scrum_tracker_statuses, :via => :post
  match '/scrum_admin/update_scrum_trackers' => "scrum_admins#update_scrum_trackers", :as => :update_scrum_trackers, :via => :post
  match '/scrum_admin/update_weekly_vacations' => "scrum_admins#update_weekly_vacation", :as => :admin_weekly_vacation
  
  # Scrum Charts
  match '/projects/:project_id/scrum_charts(.:format)' => 'scrum_charts#index', :as => :scrum_charts
  match '/projects/:project_id/scrum_charts/update_chart' => 'scrum_charts#update_chart', :as => :update_chart
  
  # Vacations
  match '/vacations' => 'vacations#index', :as => :vacations
  match '/vacations/add_weekly_vacation' => 'vacations#weekly_vacation', :as => :weekly_vacation
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  match '/vacations/add_vacation' => 'vacations#add_vacation', :as => :add_vacation
  match '/vacations/:id/delete_vacation' => 'vacations#delete_vacation', :as => :delete_vacation, :via => :delete
end

app/views/scrum/_errors.html.erb
<% if object.errors.any? %>
  <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
  <% end %>
<% end %>

app/views/scrum/_scrummer_menu.html.erb
<div id="scrum_menu" class="tabs">
	<% # highlighting scrummer label in the main menu%>
	<%= javascript_tag "select_menu_item('scrummer');"%>
	<ul id="scrummer_menu">

	<% class_attr = {}%>
	<% class_attr[@current_page] = "selected"%>

	<% if User.current.allowed_to?(:scrum_release_planing, @project)%>
		<li>
			<%= link_to "Release Planning", scrum_release_planing_path(:project_id => @project.identifier), :class => class_attr[:release_planning] %>
		</li>
	<% end%>

	<% if User.current.allowed_to?(:scrum_sprint_planing, @project)%>
		<li>
			<%= link_to "Sprint Planning", scrum_sprint_planing_path(:project_id => @project.identifier), :class => class_attr[:sprint_planning] %>
		</li>
	<% end%>
		
	<% if User.current.allowed_to?(:scrum_user_stories, @project)%>
		<li>
			<%= link_to "User Stories", scrum_user_stories_path(:project_id => @project.identifier), :class => class_attr[:user_stories] %>
		</li>
	<% end%>

	<% if User.current.allowed_to?(:scrum_charts, @project)%>
		<li>
			<%= link_to "Charts", scrum_charts_path(:project_id => @project.identifier), :class => class_attr[:charts] %>
		</li>
	<% end%>
	</ul>
</div>
<style type="text/css">
	/* Assigning Colors for issue trackers */
	<% Tracker.find_all_by_is_scrum(true).each do |tracker| %>
		.<%= tracker.scrummer_caption.to_s %>-issue .tracker {
			color: <%= tracker.color %>
		}
	<% end %>

	/* Assigning colors for issues statues */
	<% IssueStatus.find_all_by_is_scrum(true).each do |status| %>
		.status.<%= status.scrummer_caption.to_s %> {
			background-color: <%= status.color %>;
			width: <%= status.width %>px;
		}
	<% end %>
</style>

app/views/scrum/charts.html.erb
<h2>Scrum#charts</h2>

app/views/scrum/index.html.erb
<h2><%=l(:label_scrum_index)%></h2>

app/views/scrum/plan_releases.html.erb
<h2>Scrum#plan_release</h2>

app/views/scrum/plan_sprints.html.erb
<h2>Scrum#plan_iteration</h2>